@Presentation_HostAddress = http://localhost:5137

GET {{Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###

### Create a new course
POST {{Presentation_HostAddress}}/api/Course
Content-Type: application/json

{
    "name": "Introduction to Clean Architecture",
    "description": "Learn the principles and practices of Clean Architecture",
    "startDate": "2024-02-01T09:00:00",
    "endDate": "2024-05-31T17:00:00",
    "maxStudents": 30,
    "isActive": true
}

###
